[build-system]
requires = ["setuptools>=42", "wheel", "torch"]
build-backend = "setuptools.build_meta"

[project]
name = "simple_knn"
version = "0.0.1"
description = "CUDA extension for simple_knn"
requires-python = ">=3.8"
